sudo: false
language: python
python:
  - "2.7"
# use a pip cache
cache:
  directories:
  - $PWD/wheelhouse
# Tell pypi where to find wheels
env:
  global:
    - export PIP_FIND_LINKS=$PWD/wheelhouse
# command to install dependencies
install:
  - pip wheel -r requirements.txt
  - pip wheel flake8
  - pip install -r requirements.txt
  - pip install flake8
  - python setup.py install
# command to run tests
script:
  - nosetests
  - flake8 --exit-zero jiocloud
